version: '3'

services:
  app:
    image: node:10-alpine
    volumes:
      - ./:/app
    ports:
      - 4000:4000
    environment:
      - "DEBUG=*"
      - NODE_ENV=testing
    links:
      - mysql
    depends_on:
      - mysql
    working_dir: /app
    command:
      - /bin/sh
      - -c
      - |
        npm i
        npm run dev -- -L
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
